# Minimum installation
# see config-example.yml for documentation
drivers:
    mysql:
        jar:   'https://repo1.maven.org/maven2/mysql/mysql-connector-java/8.0.21/mysql-connector-java-8.0.21.jar'
        class: 'com.mysql.cj.jdbc.Driver'
        url:   'jdbc:mysql://'
        attr:  '?autoReconnect=true&useSSL=false&useUnicode=false&serverTimezone=GMT%2B1'
        escape: true

    oracle:
        jar:   'https://download.oracle.com/otn-pub/otn_software/jdbc/197/ojdbc8.jar'
        class: 'oracle.jdbc.OracleDriver'
        url:   'jdbc:oracle:thin:@'

    postgresql:
        jar:   'https://repo1.maven.org/maven2/org/postgresql/postgresql/42.2.14/postgresql-42.2.14.jar'
        class: 'org.postgresql.Driver'
        url:   'jdbc:postgresql://'

    sqlserver:
        jar:   'https://repo1.maven.org/maven2/mysql/mysql-connector-java/8.0.21/mysql-connector-java-8.0.21.jar'
        class: 'com.microsoft.sqlserver.jdbc.SQLServerDriver'
        url:   'jdbc:sqlserver://'

    sqlite:
        jar:    'https://repo1.maven.org/maven2/org/xerial/sqlite-jdbc/3.32.3/sqlite-jdbc-3.32.3.jar'
        class:  'org.sqlite.JDBC'
        url:    'jdbc:sqlite:'
encryption: false
